### ISSUE TITLE
Use new discord slash commands

### ISSUE THREAD

**Issue by jNullj** [jNullj/Pikabot#18]
Discord now has / commands which are a better way to interact with bots.
Discord.js already implimented this.
[this guide](https://gist.github.com/advaith1/287e69c3347ef5165c0dbde00aa305d2) also seems useful.
Lets add that.

**Comment by MooImApig** [comment]
I want to try

**Comment by jNullj** [comment]
There might have been changes to slash comands in discord.js. see issue #19 for more info.
We need to decide if we want to stay on v12 for a while and complete slash comands soon or prospone this until after the v13 update

**Comment by jNullj** [comment]
Issue #19 is solved on master you can now solve this issue.
Notice that there might have been changes to slash commands in version 13.1 of discord.js, you can use their docs [here](https://discord.js.org/#/docs/main/stable/general/welcome) or [guide](https://discordjs.guide/)
